interval: Interval.o GenericHeap.o
	g++ -o interval Interval.o GenericHeap.o

Interval.o: Interval.cpp Interval.hpp
	g++ -c -Wall -ansi -pedantic -std=c++20

GenericHeap.o: GenericHeap.cpp GenericHeap.hpp
	g++ -c -Wall -ansi -pedantic -std=c++20